version: '3'
services:

  influxdb:
    # must use version < 2.0 due to modified authentication
    image: influxdb:1.8.6
    restart: always
    networks:
      monitor:
        ipv4_address: 172.28.1.2
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
      - "8082:8082"
      # UDP Port
      - "8089:8089/udp"
    volumes:
      - ./influxdb/data:/var/lib/influxdb
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "2m"

  crawler:
    restart: on-failure
    image: nucypher-monitor:latest
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    ports:
      - "9151:9151"
      - "9555:9555"
    command: ["crawl",
              "--influx-host", "172.28.1.2",
              "--provider", "${WEB3_PROVIDER_URI}",
              "--network", "${NUCYPHER_NETWORK}"]
    networks:
      monitor:
        ipv4_address: 172.28.1.3
    volumes:
      - .:/code
      - "nucypher_datadir:/root/.local/share/nucypher"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "15m"
    depends_on:
      - influxdb

  web:
    restart: on-failure
    image: nucypher-monitor:latest
    command: ["dashboard",
              "--debug",
              "--influx-host", "172.28.1.2",
              "--crawler-host", "172.28.1.3",
              "--provider", "${WEB3_PROVIDER_URI}",
              "--network", "${NUCYPHER_NETWORK}",
              "--tls-key-filepath", "/etc/letsencrypt/privkey.pem",
              "--certificate-filepath", "/etc/letsencrypt/fullchain.pem"]
    networks:
      monitor:
        ipv4_address: 172.28.1.4
    ports:
      - "443:12500"
    volumes:
      - .:/code
      - "nucypher_datadir:/root/.local/share/nucypher"
      - "${NUCYPHER_LETSENCRYPT_DIR}:/etc/letsencrypt/"
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "10m"
    depends_on:
      - crawler
      - influxdb


networks:
  monitor:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
    nucypher_datadir:
