version: '3'
services:

#  crawler:
#    restart: on-failure
#    image: nucypher-monitor:latest
#    build:
#      context: ..
#      dockerfile: ./deploy/Dockerfile
#    ports:
#      - "9151:9151"
#      - "9555:9555"
#    command: ["crawl",
#              "--provider", "${WEB3_PROVIDER_URI}",
#              "--network", "${NUCYPHER_NETWORK}"]
#    networks:
#      monitor:
#        ipv4_address: 172.28.1.3
#    volumes:
#      - .:/code
#      - "nucypher_datadir:/root/.local/share/nucypher"
#    logging:
#      driver: "json-file"
#      options:
#        max-file: "5"
#        max-size: "15m"

  web:
    restart: on-failure
    image: nucypher-monitor:latest
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    command: ["dashboard",
              "--debug",
              "--provider", "${WEB3_PROVIDER_URI}",
              "--network", "${NUCYPHER_NETWORK}",
              "--tls-key-filepath", "/etc/letsencrypt/privkey.pem",
              "--certificate-filepath", "/etc/letsencrypt/fullchain.pem"]
    networks:
      monitor:
        ipv4_address: 172.28.1.4
    ports:
      - "443:12500"
    volumes:
      - .:/code
      - "nucypher_datadir:/root/.local/share/nucypher"
      - "${NUCYPHER_LETSENCRYPT_DIR}:/etc/letsencrypt/"
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "10m"

networks:
  monitor:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
    nucypher_datadir:
